# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dc70qId1DqM0k9kParKSvMvp4Q4a1Ovb?resourcekey=0-lethPwjPxQEn7DiFVDPMuw
"""

import os
import gdown
import joblib
import pandas as pd
import numpy as np
from flask import Flask, render_template, request, jsonify
from model import TicketRecommendationSystem
import nltk
import traceback

# Download NLTK data
print("Downloading NLTK resources...")
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
print("NLTK resources downloaded!")

app = Flask(__name__)

# Global recommender object
recommender = None

def download_from_drive():
    """Download model and CSV from Google Drive"""
    print("Checking for files from Google Drive...")

    # Your Google Drive file IDs (I can see them in your code)
    MODEL_FILE_ID = "10dtSRjjsE-42sLFDnfOj8WKLu99YuZ-A"  # From your code
    CSV_FILE_ID = "YOUR_CSV_FILE_ID"  # You need to get this from Google Drive

    # Download model file if not exists
    if not os.path.exists("ticket_recommender_model.joblib"):
        print("Downloading model from Google Drive...")
        model_url = f"https://drive.google.com/uc?id=10dtSRjjsE-42sLFDnfOj8WKLu99YuZ-A"
        gdown.download(model_url, "ticket_recommender_model.joblib", quiet=False)
        print("✅ Model downloaded!")

    # Download CSV file if not exists
    if not os.path.exists("merged_data.csv"):
        print("Downloading CSV from Google Drive...")
        csv_url = f"https://drive.google.com/uc?id=1JsSCqQomfIelhSfO9eHlbyDGbuRqfzMX"
        gdown.download(csv_url, "merged_data.csv", quiet=False)
        print("✅ CSV downloaded!")

def load_recommender():
    """Load the recommendation model"""
    global recommender
    try:
        print("Loading recommendation system...")
        recommender = TicketRecommendationSystem()

        # Check if model file exists
        if os.path.exists("ticket_recommender_model.joblib"):
            recommender.load_model("ticket_recommender_model.joblib")
            print("✅ Model loaded successfully!")
            return True
        else:
            print("❌ Model file not found!")
            return False
    except Exception as e:
        print(f"❌ Error loading model: {e}")
        traceback.print_exc()
        return False

@app.route('/')
def home():
    """Serve the HTML frontend"""
    return render_template('index.html')

@app.route('/api/find_similar_tickets', methods=['POST'])
def find_similar_tickets():
    """API endpoint to find similar tickets"""
    global recommender

    if recommender is None:
        return jsonify({"error": "Recommendation system not loaded"}), 500

    try:
        data = request.get_json()

        if not data or 'description' not in data:
            return jsonify({"error": "No description provided"}), 400

        description = data['description'].strip()

        if not description:
            return jsonify({"error": "Empty description"}), 400

        if len(description) < 10:
            return jsonify({"error": "Description too short (minimum 10 characters)"}), 400

        # Find similar tickets
        results = recommender.find_similar_tickets(
            query_description=description,
            top_n=10,
            similarity_threshold=0.5
        )

        return jsonify(results)

    except Exception as e:
        print(f"Error: {e}")
        traceback.print_exc()
        return jsonify({"error": str(e)}), 500

@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    return jsonify({
        "status": "healthy",
        "model_loaded": recommender is not None
    })

if __name__ == '__main__':
    # Download files from Google Drive first
    download_from_drive()

    # Load the recommender
    if load_recommender():
        port = int(os.environ.get('PORT', 5000))
        app.run(host='0.0.0.0', port=port, debug=False)
    else:
        print("❌ Failed to load recommender. Exiting.")
        exit(1)