# -*- coding: utf-8 -*-
"""Guts Randomization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZcLpxNCy9QC-BjrCM5rFcJeRh3jkTnp?resourcekey=0-QGehfDfT4haYGdZCToNBFA
"""

# Import necessary libraries
import pandas as pd
import numpy as np
from google.colab import drive
import re
import string
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import normalize
from sklearn.neighbors import NearestNeighbors
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import pickle
import joblib
import os
import time
import nltk

# Download required NLTK data
print("Downloading NLTK resources...")
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab')
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
print("NLTK resources downloaded successfully!\n")

class TextPreprocessor:
    def __init__(self):
        self.stop_words = set(stopwords.words('english'))
        self.lemmatizer = WordNetLemmatizer()

    def preprocess_text(self, text):
        """Advanced text preprocessing with multiple cleaning steps"""
        if not isinstance(text, str) or pd.isna(text):
            return ""

        # Convert to lowercase
        text = text.lower()

        # Remove URLs
        text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

        # Remove email addresses
        text = re.sub(r'\S+@\S+', '', text)

        # Remove special characters and digits but keep basic punctuation for context
        text = re.sub(r'[^a-zA-Z\s\.\,\!\?]', '', text)

        # Remove extra whitespace
        text = re.sub(r'\s+', ' ', text).strip()

        # Tokenize
        tokens = word_tokenize(text)

        # Remove stopwords and short tokens
        tokens = [token for token in tokens if token not in self.stop_words and len(token) > 2]

        # Lemmatization
        tokens = [self.lemmatizer.lemmatize(token) for token in tokens]

        return ' '.join(tokens)

    def batch_preprocess(self, texts, batch_size=1000):
        """Preprocess texts in batches to manage memory"""
        processed_texts = []
        total_batches = (len(texts) + batch_size - 1) // batch_size

        for i in range(0, len(texts), batch_size):
            batch = texts[i:i + batch_size]
            processed_batch = [self.preprocess_text(text) for text in batch]
            processed_texts.extend(processed_batch)

            if (i // batch_size) % 10 == 0:
                print(f"Processed {min(i + batch_size, len(texts))}/{len(texts)} texts")

        return processed_texts

class TicketRecommendationSystem:
    def __init__(self):
        self.vectorizer = None
        self.svd = None
        self.nn_index = None
        self.ticket_data = None
        self.embedding_matrix = None
        self.ticket_ids = None
        self.preprocessor = TextPreprocessor()

    def load_data(self, file_path=r"merged_data.csv"):
        """Load and validate the CSV data with proper error handling"""
        print(f"Loading data from {file_path}...")

        try:
            # Read CSV file with error handling
            self.ticket_data = pd.read_csv(file_path)
            print(f"✓ Data loaded successfully! Shape: {self.ticket_data.shape}")
            print(f"✓ Columns found: {list(self.ticket_data.columns)}")

            # Display sample data
            print("\nSample data from CSV:")
            print(self.ticket_data.head(3))

            # Check required columns - handle different column name cases
            required_columns = ['ticket_id', 'description']
            actual_columns = [col.lower() for col in self.ticket_data.columns]

            # Try to find matching columns (case-insensitive)
            ticket_id_col = None
            description_col = None

            for col in self.ticket_data.columns:
                if 'ticket' in col.lower() and 'id' in col.lower():
                    ticket_id_col = col
                elif 'desc' in col.lower():
                    description_col = col

            if not ticket_id_col or not description_col:
                raise ValueError("Could not find required columns. Please ensure your CSV has columns for ticket ID and description.")

            print(f"✓ Using '{ticket_id_col}' as ticket_id column")
            print(f"✓ Using '{description_col}' as description column")

            # Rename columns to standard names for consistency
            self.ticket_data = self.ticket_data.rename(columns={
                ticket_id_col: 'ticket_id',
                description_col: 'description'
            })

            # Check for missing values
            print("\nChecking data quality...")
            missing_tickets = self.ticket_data['ticket_id'].isna().sum()
            missing_descriptions = self.ticket_data['description'].isna().sum()
            duplicate_tickets = self.ticket_data['ticket_id'].duplicated().sum()

            print(f"Missing ticket IDs: {missing_tickets}")
            print(f"Missing descriptions: {missing_descriptions}")
            print(f"Duplicate ticket IDs: {duplicate_tickets}")

            # Remove rows with missing descriptions
            if missing_descriptions > 0:
                original_count = len(self.ticket_data)
                self.ticket_data = self.ticket_data.dropna(subset=['description'])
                print(f"Removed {original_count - len(self.ticket_data)} rows with missing descriptions")

            # Remove duplicates if any
            if duplicate_tickets > 0:
                original_count = len(self.ticket_data)
                self.ticket_data = self.ticket_data.drop_duplicates(subset=['ticket_id'])
                print(f"Removed {original_count - len(self.ticket_data)} duplicate ticket IDs")

            # Check data types
            print(f"\nData types:")
            print(f"ticket_id: {self.ticket_data['ticket_id'].dtype}")
            print(f"description: {self.ticket_data['description'].dtype}")

            # Convert ticket_id to string to handle mixed types
            self.ticket_data['ticket_id'] = self.ticket_data['ticket_id'].astype(str)

            print(f"✓ Final dataset shape: {self.ticket_data.shape}")
            print(f"✓ Total tickets available for processing: {len(self.ticket_data)}")

        except FileNotFoundError:
            raise FileNotFoundError(f"File {file_path} not found. Please ensure 'merged_data.csv' is in the same directory.")
        except Exception as e:
            raise Exception(f"Error loading data: {str(e)}")

    def preprocess_data(self):
        """Preprocess all descriptions with progress tracking"""
        print("\nStarting text preprocessing...")
        start_time = time.time()

        # Get descriptions
        descriptions = self.ticket_data['description'].tolist()

        # Preprocess in batches
        self.ticket_data['processed_description'] = self.preprocessor.batch_preprocess(descriptions)

        # Remove empty processed descriptions
        initial_count = len(self.ticket_data)
        self.ticket_data = self.ticket_data[self.ticket_data['processed_description'].str.len() > 0]
        removed_count = initial_count - len(self.ticket_data)

        if removed_count > 0:
            print(f"Removed {removed_count} rows with empty processed descriptions")

        end_time = time.time()
        print(f"✓ Text preprocessing completed in {end_time - start_time:.2f} seconds")
        print(f"✓ Processed dataset shape: {self.ticket_data.shape}")

        # Show sample of processed text
        print("\nSample of processed text:")
        for i in range(min(2, len(self.ticket_data))):
            original = self.ticket_data['description'].iloc[i]
            processed = self.ticket_data['processed_description'].iloc[i]
            print(f"Original: {original[:80]}...")
            print(f"Processed: {processed}")
            print()

    def build_model(self):
        """Build the recommendation model"""
        print("Building recommendation model...")
        start_time = time.time()

        # Create TF-IDF vectors
        print("Creating TF-IDF vectors...")
        self.vectorizer = TfidfVectorizer(
            max_features=50000,
            min_df=2,
            max_df=0.95,
            ngram_range=(1, 2),
            sublinear_tf=True
        )

        tfidf_matrix = self.vectorizer.fit_transform(
            self.ticket_data['processed_description']
        )
        print(f"TF-IDF matrix shape: {tfidf_matrix.shape}")

        # Dimensionality reduction using SVD
        print("Applying dimensionality reduction...")
        self.svd = TruncatedSVD(n_components=300, random_state=42)
        self.embedding_matrix = self.svd.fit_transform(tfidf_matrix)

        # Normalize embeddings for cosine similarity
        self.embedding_matrix = normalize(self.embedding_matrix)

        # Build nearest neighbors index for fast searching
        print("Building nearest neighbors index...")
        self.nn_index = NearestNeighbors(n_neighbors=10, metric='cosine', n_jobs=-1)
        self.nn_index.fit(self.embedding_matrix)

        self.ticket_ids = self.ticket_data['ticket_id'].values

        end_time = time.time()
        print(f"✓ Model building completed in {end_time - start_time:.2f} seconds")
        print(f"✓ Explained variance ratio: {self.svd.explained_variance_ratio_.sum():.4f}")
        print(f"✓ Vocabulary size: {len(self.vectorizer.get_feature_names_out())}")

    def find_similar_tickets(self, query_description, top_n=5, similarity_threshold=0.7):
        """Find similar tickets for a given description"""
        if self.vectorizer is None or self.svd is None:
            raise ValueError("Model not trained. Please call build_model first.")

        # Preprocess query
        processed_query = self.preprocessor.preprocess_text(query_description)

        if not processed_query:
            return {"error": "Query resulted in empty text after preprocessing"}

        # Transform query to same vector space
        query_tfidf = self.vectorizer.transform([processed_query])
        query_embedding = self.svd.transform(query_tfidf)
        query_embedding = normalize(query_embedding)

        # Find nearest neighbors
        distances, indices = self.nn_index.kneighbors(query_embedding, n_neighbors=top_n)

        results = []
        for dist, idx in zip(distances[0], indices[0]):
            similarity_score = 1 - dist # Convert distance to similarity

            if similarity_score >= similarity_threshold:
                results.append({
                    'ticket_id': str(self.ticket_ids[idx]),
                    'similarity_score': float(similarity_score),
                    'original_description': str(self.ticket_data['description'].iloc[idx]),
                    'processed_description': str(self.ticket_data['processed_description'].iloc[idx])
                })

        return results

    def save_model(self, filepath="ticket_recommender_model.joblib"):
        """Save the trained model"""
        model_data = {
            'vectorizer': self.vectorizer,
            'svd': self.svd,
            'nn_index': self.nn_index,
            'ticket_ids': self.ticket_ids,
            'ticket_data': self.ticket_data,
            'embedding_matrix': self.embedding_matrix
        }

        joblib.dump(model_data, filepath)
        print(f"✓ Model saved to {filepath}")
        print(f"✓ Model size: {os.path.getsize(filepath) / (1024*1024):.2f} MB")

    def load_model(self, filepath="ticket_recommender_model.joblib"):
        """Load a pre-trained model"""
        if not os.path.exists(filepath):
            raise FileNotFoundError(f"Model file {filepath} not found")

        print(f"Loading model from {filepath}...")
        model_data = joblib.load(filepath)

        self.vectorizer = model_data['vectorizer']
        self.svd = model_data['svd']
        self.nn_index = model_data['nn_index']
        self.ticket_ids = model_data['ticket_ids']
        self.ticket_data = model_data['ticket_data']
        self.embedding_matrix = model_data['embedding_matrix']

        print("✓ Model loaded successfully!")
        print(f"✓ Loaded data shape: {self.ticket_data.shape}")
        print(f"✓ Vocabulary size: {len(self.vectorizer.get_feature_names_out())}")

def train_and_save_model():
    """Function to train the model using the CSV file and save it"""
    print("=" * 60)
    print("TRAINING NEW MODEL FROM merged_data.csv")
    print("=" * 60)

    # Initialize the recommendation system
    recommender = TicketRecommendationSystem()

    # Load data from your CSV file
    csv_file_path = r"merged_data.csv" # Your CSV file name
    recommender.load_data(csv_file_path)

    # Preprocess the data
    recommender.preprocess_data()

    # Build the model
    recommender.build_model()

    # Save the model for future use
    model_save_path = "ticket_recommender_model.joblib"
    recommender.save_model(model_save_path)

    print(f"\n✓ Model training completed and saved to {model_save_path}")

    # Test with a sample query
    print("\nTesting with sample query...")
    test_query = "computer running slow freezing"
    results = recommender.find_similar_tickets(test_query, top_n=3)

    if results:
        print(f"Query: '{test_query}'")
        for i, result in enumerate(results, 1):
            print(f"{i}. Ticket {result['ticket_id']} (similarity: {result['similarity_score']:.3f})")

    return recommender

def load_and_use_model():
    """Function to load the pre-trained model and use it with CSV data"""
    print("=" * 60)
    print("LOADING PRE-TRAINED MODEL")
    print("=" * 60)

    # Initialize the recommendation system
    recommender = TicketRecommendationSystem()

    # Load the pre-trained model
    model_path = "ticket_recommender_model.joblib"
    recommender.load_model(model_path)

    # Example queries that might match your ticket data
    test_queries = []

    print("Testing the recommendation system with sample queries:\n")

    for i, query in enumerate(test_queries, 1):
        print(f"Query {i}: '{query}'")
        similar_tickets = recommender.find_similar_tickets(query, top_n=2)

        if 'error' in similar_tickets:
            print(f" Error: {similar_tickets['error']}")
        elif not similar_tickets:
            print(" No similar tickets found above threshold")
        else:
            for j, ticket in enumerate(similar_tickets, 1):
                print(f" {j}. Ticket ID: {ticket['ticket_id']}")
                print(f" Similarity: {ticket['similarity_score']:.3f}")
                print(f" Description: {ticket['original_description'][:70]}...")
        print()

    return recommender

def interactive_query_mode(recommender):
    """Interactive mode for querying the recommendation system"""
    print("\n" + "="*50)
    print("INTERACTIVE QUERY MODE")
    print("Enter your ticket description (or 'quit' to exit)")
    print("="*50)

    while True:
        user_input = input("\nEnter ticket description: ").strip()

        if user_input.lower() in ['quit', 'exit', 'q']:
            print("Exiting interactive mode...")
            break

        if not user_input:
            print("Please enter a description.")
            continue

        print(f"\nSearching for similar tickets to: '{user_input}'")

        try:
            results = recommender.find_similar_tickets(user_input, top_n=5)

            if 'error' in results:
                print(f"Error: {results['error']}")
            elif not results:
                print("No similar tickets found above the similarity threshold.")
            else:
                print(f"\nFound {len(results)} similar tickets:")
                for i, ticket in enumerate(results, 1):
                    print(f"{i}. Ticket ID: {ticket['ticket_id']}")
                    print(f" Similarity Score: {ticket['similarity_score']:.3f}")
                    print(f" Original Description: {ticket['original_description'][:100]}...")
                    print()

        except Exception as e:
            print(f"Error processing query: {str(e)}")

# def main():
#     """Main function to run the recommendation system with CSV data"""
#     print("TICKET RECOMMENDATION SYSTEM")
#     print("Using data from: merged_data.csv")
#     print("=" * 60)

#     # Check if model already exists
#     model_path = "ticket_recommender_model.joblib"
#     csv_path = "merged_data.csv"

#     # Check if CSV file exists
#     if not os.path.exists(csv_path):
#         print(f"❌ Error: CSV file '{csv_path}' not found!")
#         print("Please ensure 'merged_data.csv' is in the same directory.")
#         return

#     if os.path.exists(model_path):
#         print("✓ Pre-trained model found.")
#         choice = input("Do you want to (1) Load existing model or (2) Train new model? [1/2]: ")

#         if choice == "2":
#             print("Training new model...")
#             recommender = train_and_save_model()
#         else:
#             print("Loading existing model...")
#             recommender = load_and_use_model()
#     else:
#         print("No pre-trained model found. Training new model from CSV...")
#         recommender = train_and_save_model()

#     # Enter interactive mode
#     interactive_query_mode(recommender)

# if __name__ == "__main__":
#     main()

# Updated main function
def main():
    """Main function to run the recommendation system with CSV data"""
    print("TICKET RECOMMENDATION SYSTEM")
    print("Using data from: merged_data.csv")
    print("=" * 60)

    # Check if Google Drive is mounted and a model exists there
    model_drive_path = '/content/drive/My Drive/ticket_recommender_model.joblib'
    csv_path = "merged_data.csv"

    # Check if CSV file exists
    if not os.path.exists(csv_path):
        print(f"❌ Error: CSV file '{csv_path}' not found!")
        print("Please ensure 'merged_data.csv' is in the same directory.")
        return

    recommender = None

    # Check if the model file exists in Google Drive
    if os.path.exists(model_drive_path):
        print("✓ Pre-trained model found in Google Drive.")
        choice = input("Do you want to (1) Load existing model or (2) Train new model? [1/2]: ")

        if choice == "2":
            print("Training new model...")
            recommender = train_and_save_model()
            # After training, save the new model to Drive
            print("Saving newly trained model to Google Drive...")
            recommender.save_model(model_drive_path)

        else:
            print("Loading existing model...")
            recommender = TicketRecommendationSystem()
            recommender.load_model(model_drive_path)

    else:
        print("No pre-trained model found. Training new model from CSV...")
        recommender = train_and_save_model()
        # After training, save the new model to Drive
        print("Saving newly trained model to Google Drive...")
        recommender.save_model(model_drive_path)

    # Enter interactive mode only if a recommender object was created
    if recommender:
        interactive_query_mode(recommender)

if __name__ == "__main__":
    # Mount Google Drive at the very beginning
    drive.mount('/content/drive')
    main()

